In [39]:
! pip install pandas

In [40]:
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt
import pandas as pd

In [41]:
def normal_equation(x,y):
    h=inv(x.T@x)
    w=h@x.T@y
    return w

def lr_predict(x,w):
    return np.dot(x,w)

def closed_form(x,y):
    w=normal_equation(x,y)
    y_hat=lr_predict(x,w)
    return y_hat
def mse_loss(y_hat,y):
    error=y_hat-y
    return np.sum(error*error)/error.shape[0]

In [42]:
df=pd.read_csv('weather.csv')
df.head()


City  Temp(F)  Rainfall(mm)  Humidity(%)  Apples(ton)  Oranges(ton)
0      Semnan     73.0          67.0         43.0         56.0          70.0
1    Golestan     91.0          88.0         64.0         81.0         101.0
2       Gilan     87.0         134.0         58.0        119.0         133.0
3     Ghazvin    102.0          43.0         37.0         22.0          37.0
4  Mazandaran     69.0          96.0         70.0        103.0         119.0

In [43]:
x=df[[ 'Rainfall(mm)','Temp(F)','Humidity(%)']].values
x

array([[ 67.,  73.,  43.],
       [ 88.,  91.,  64.],
       [134.,  87.,  58.],
       [ 43., 102.,  37.],
       [ 96.,  69.,  70.]])

In [44]:
y=df['Apples(ton)']
y

0     56.0
1     81.0
2    119.0
3     22.0
4    103.0
Name: Apples(ton), dtype: float64

In [45]:
ones=np.ones((x.shape))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
ones=np.ones((x.shape[0],(1)))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [47]:
x_new=np.concatenate((ones,x),axis=1)
x_new

array([[  1.,  67.,  73.,  43.],
       [  1.,  88.,  91.,  64.],
       [  1., 134.,  87.,  58.],
       [  1.,  43., 102.,  37.],
       [  1.,  96.,  69.,  70.]])

In [48]:
y_hat=closed_form(x_new,y)
y_hat

array([ 56.89083779,  82.37913697, 118.73717962,  21.11595158,
       101.87689403])

In [49]:
mse_loss(y_hat,y)

0.9615187875649459

In [50]:
x=df[['Rainfall(mm)','Temp(F)','Humidity(%)']].values
y=df['Oranges(ton)']

In [51]:
onse=np.ones((x.shape[0],1))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [52]:
x_new=np.concatenate((ones,x),axis=1)
x_new

array([[  1.,  67.,  73.,  43.],
       [  1.,  88.,  91.,  64.],
       [  1., 134.,  87.,  58.],
       [  1.,  43., 102.,  37.],
       [  1.,  96.,  69.,  70.]])

In [53]:
y_hat=closed_form(x_new,y)

mse_loss(y_hat,y)

0.004723656551456912

In [54]:
def calc_gradient(x,error):
    gradient=np.dot(x.T,error)
    return gradient

def update_weights(w,lr,gradient):
    new_weights=w-lr*gradient
    return new_weights

In [55]:
x.shape

(5, 3)

In [56]:
def train_lr_bgd(x,y,w,n_epochs,lr):
    losses=[]

    for i in range(n_epochs):
        predictions=lr_predict(x,w)
        error=predictions-y

        loss=mse_loss(predictions,y)
        losses.append(loss)


        gradient=calc_gradient(x,error)
        w=update_weights(w,lr,gradient)

    return w,losses
       



In [57]:
lr=0.4
n_epochs=1000
w0=np.random.rand(4)

w,losses=train_lr_bgd(x_new,y,w0,n_epochs,lr)
losses[-1]

C:\Users\kalan\AppData\Local\Temp\ipykernel_6568\2787503870.py:6: RuntimeWarning: invalid value encountered in subtract
  new_weights=w-lr*gradient


0.0

In [58]:
x_new


array([[  1.,  67.,  73.,  43.],
       [  1.,  88.,  91.,  64.],
       [  1., 134.,  87.,  58.],
       [  1.,  43., 102.,  37.],
       [  1.,  96.,  69.,  70.]])

In [59]:
numbers= np.array([[73, 67, 43, 56, 70],
                   [91, 88, 64, 81, 101],
                   [87, 134, 58, 119, 133],
                   [102, 43, 37, 22, 37],
                   [102, 43, 37, 22, 37],
                   [69, 96, 70, 103, 119]], dtype='float32')
x=numbers[:,:4]
y=numbers[:,4]

In [60]:
ones=np.ones((x.shape[0],1))
x_new=np.concatenate((ones,x),axis=1)
x_new

array([[  1.,  73.,  67.,  43.,  56.],
       [  1.,  91.,  88.,  64.,  81.],
       [  1.,  87., 134.,  58., 119.],
       [  1., 102.,  43.,  37.,  22.],
       [  1., 102.,  43.,  37.,  22.],
       [  1.,  69.,  96.,  70., 103.]])

In [61]:
y_hat=closed_form(x,y)
mse_loss(y_hat,y)


0.04944289724032084

In [62]:
lr=0.000009
epochs=1000
W0=np.random.rand(5)
W,losses=train_lr_bgd(x_new,y,W0,epochs,lr)
losses[-1]

0.5072850091997841

In [63]:
t0=5
t1=50000

def learning_schedule(t):
    return t0/(t+t1)

#def train_lr_bgd(X,Y,W,n_epochs,lr):

def train_lr_sgd(X,Y,W,n_epochs):
    losses=[]
    m=X.shape[0]
    for epoch in range(n_epochs):
        for iteration in range(m):
            random_index = np.random.randint(m)
            xi=X[random_index:random_index+1]
            yi=Y[random_index:random_index+1]

            predictions=lr_predict(xi,W)
            error=predictions-yi

            loss=mse_loss(predictions,yi)
            losses.append(loss)


            lr = learning_schedule(epoch*m + iteration)

            gradient=calc_gradient(xi,error)
            W=update_weights(W,lr,gradient)

    return W,losses


In [64]:
t0=5
t1=500000
epochs=10
w0=np.random.rand(5)
w,losses=train_lr_sgd(x_new,y,w0,n_epochs)
losses[-1]

0.0016741034449155488